import { TG, DZ, SX, WX, NY, GW, ZW, ZC, SS } from './shared.js';
import { jqDate, getMonthPillar, getDayPillarIndex } from './calendar.js';

function mkBazi(y,m,d,hourZhi){const mp=getMonthPillar(y,m,d);const yp=mp.yp;const ygi=((yp-4)%10+10)%10;const yzi=((yp-4)%12+12)%12;const mzi=(mp.mi+2)%12;const monthGanBase=[2,4,6,8,0];const mgi=(monthGanBase[ygi%5]+mp.mi)%10;const dji=getDayPillarIndex(y,m,d);const dgi=dji%10;const dzi=dji%12;const hourGanBase=[0,2,4,6,8];const hgi=(hourGanBase[dgi%5]+hourZhi)%10;const nyi=((yp-4)%60+60)%60;return{Y:{g:TG[ygi],z:DZ[yzi],gi:ygi,zi:yzi},M:{g:TG[mgi],z:DZ[mzi],gi:mgi,zi:mzi},D:{g:TG[dgi],z:DZ[dzi],gi:dgi,zi:dzi},H:{g:TG[hgi],z:DZ[hourZhi],gi:hgi,zi:hourZhi},dj:dji,ny:NY[nyi],sx:SX[yzi]};}
function mkWx(b){const c={木:0,火:0,土:0,金:0,水:0};[b.Y.g,b.M.g,b.D.g,b.H.g].forEach(g=>c[GW[g]]+=1);[b.Y.z,b.M.z,b.D.z,b.H.z].forEach(z=>c[ZW[z]]+=1);[b.Y.z,b.M.z,b.D.z,b.H.z].forEach(z=>{const cg=ZC[z];if(cg[0])c[GW[cg[0]]]+=0.6;if(cg[1])c[GW[cg[1]]]+=0.3;if(cg[2])c[GW[cg[2]]]+=0.1;});const dw=GW[b.D.g];let s='木',w='木';WX.forEach(x=>{if(c[x]>c[s])s=x;if(c[x]<c[w])w=x;});const t=Object.values(c).reduce((a,b)=>a+b,0);const SH={木:'火',火:'土',土:'金',金:'水',水:'木'};const KE={木:'土',火:'金',土:'水',金:'木',水:'火'};const BS={木:'水',火:'木',土:'火',金:'土',水:'金'};const BK={木:'金',火:'水',土:'木',金:'火',水:'土'};const monthWx=ZW[b.M.z];const deLing=(monthWx===dw||BS[dw]===monthWx)?2:(SH[dw]===monthWx?0.5:0);const selfP=c[dw]+c[BS[dw]]+deLing;const otherP=t-c[dw]-c[BS[dw]]+(2-deLing);const st=selfP>=otherP*0.85;let ys,xs;if(st){ys=SH[dw];xs=KE[dw];}else{ys=BS[dw];xs=dw;}return{c,dw,st,s,w,ys,xs,t,KE,SH,BS,BK,deLing};}
function mkSs(b){const d=b.D.g,t=SS[d];return{yg:t[b.Y.g],mg:t[b.M.g],hg:t[b.H.g],yzc:ZC[b.Y.z].map(g=>({g,s:t[g]})),mzc:ZC[b.M.z].map(g=>({g,s:t[g]})),dzc:ZC[b.D.z].map(g=>({g,s:t[g]})),hzc:ZC[b.H.z].map(g=>({g,s:t[g]}))};}
function mkShenSha(b){const r=[];const dz=DZ[b.D.zi],tg=TG[b.D.gi];const xunK={0:[10,11],1:[10,11],2:[0,1],3:[0,1],4:[2,3],5:[2,3],6:[4,5],7:[4,5],8:[6,7],9:[6,7]};const xk=xunK[Math.floor(b.dj/10)];if(xk)r.push({n:'空亡',v:DZ[xk[0]]+DZ[xk[1]],t:'日柱旬中空亡，多主漂泊、精神空虛，亦有机缘灵性'});const thMap={子:'酉',丑:'午',寅:'卯',卯:'子',辰:'酉',巳:'午',午:'卯',未:'子',申:'酉',酉:'午',戌:'卯',亥:'子'};const th=thMap[dz];if(th)r.push({n:'桃花',v:th,t:'人缘、感情、魅力之星'});const ymMap={子:'寅',丑:'亥',寅:'申',卯:'巳',辰:'寅',巳:'亥',午:'申',未:'巳',申:'寅',酉:'亥',戌:'申',亥:'巳'};const ym=ymMap[dz];if(ym)r.push({n:'驿马',v:ym,t:'变动、奔波、远行之星'});const tyMap={甲:'丑未',戊:'丑未',庚:'丑未',乙:'子申',己:'子申',丙:'亥酉',丁:'亥酉',壬:'卯巳',癸:'卯巳',辛:'午寅'};const ty=tyMap[tg];if(ty)r.push({n:'天乙贵人',v:ty,t:'逢凶化吉、贵人扶助'});const wcMap={甲:'巳',乙:'午',丙:'申',戊:'申',丁:'酉',己:'酉',庚:'亥',辛:'子',壬:'寅',癸:'卯'};const wc=wcMap[tg];if(wc)r.push({n:'文昌',v:wc,t:'学业、功名、文艺之星'});const jxMap={子:'子',丑:'酉',寅:'午',卯:'卯',辰:'子',巳:'酉',午:'午',未:'卯',申:'子',酉:'酉',戌:'午',亥:'卯'};const jx=jxMap[dz];if(jx)r.push({n:'将星',v:jx,t:'权威、领导、管理之星'});const hgMap={子:'辰',丑:'丑',寅:'戌',卯:'未',辰:'辰',巳:'丑',午:'戌',未:'未',申:'辰',酉:'丑',戌:'戌',亥:'未'};const hg=hgMap[dz];if(hg)r.push({n:'华盖',v:hg,t:'孤独、宗教、艺术、玄学之星'});const tyi=DZ[(b.M.zi+11)%12];r.push({n:'天医',v:tyi,t:'健康、医学、疗愈之星'});const hyMap={甲:'午',乙:'午',丙:'寅',丁:'未',戊:'辰',己:'辰',庚:'戌',辛:'酉',壬:'子',癸:'申'};const hy=hyMap[tg];if(hy)r.push({n:'红艳',v:hy,t:'情感丰富、风流多情'});const kg=['庚辰','庚戌','壬辰','戊戌'];if(kg.includes(b.D.g+b.D.z))r.push({n:'魁罡',v:b.D.g+b.D.z,t:'刚烈、聪明、果断，女命逢之婚姻多波折'});const yrMap={甲:'卯',乙:'寅',丙:'午',丁:'巳',戊:'午',己:'巳',庚:'酉',辛:'申',壬:'子',癸:'亥'};const yr=yrMap[tg];if(yr)r.push({n:'羊刃',v:yr,t:'刚强、锐利、胆大，喜七杀配合'});return r;}
function mkDy(b,gn,y){const yangGan=b.Y.gi%2===0;const isMale=gn==='male';const fw=(yangGan&&isMale)||(!yangGan&&!isMale);const bd=document.getElementById('bDate').value;const[by,bm,bd2]=bd.split('-').map(Number);const bObj=new Date(by,bm-1,bd2);let minDays=365;for(let i=0;i<12;i++){const j=jqDate(by,i);if(!j)continue;const jDate=new Date(by,j[0]-1,j[1]);if(fw){let diff=Math.round((jDate-bObj)/86400000);if(diff<=0){const j2=jqDate(by+1,i);if(j2){diff=Math.round((new Date(by+1,j2[0]-1,j2[1])-bObj)/86400000);}}if(diff>0&&diff<minDays)minDays=diff;}else{let diff=Math.round((bObj-jDate)/86400000);if(diff<=0){const j2=jqDate(by-1,i);if(j2){diff=Math.round((bObj-new Date(by-1,j2[0]-1,j2[1]))/86400000);}}if(diff>0&&diff<minDays)minDays=diff;}}const sa=Math.max(1,Math.round(minDays/3));const ds=[];for(let i=0;i<10;i++){const o=fw?(i+1):-(i+1);ds.push({g:TG[((b.M.gi+o)%10+10)%10],z:DZ[((b.M.zi+o)%12+12)%12],as:sa+i*10,ae:sa+i*10+9,ys:y+sa+i*10,ye:y+sa+i*10+9});}return{ds,sa};}
function mkLn(cy){const r=[];for(let y=cy-2;y<=cy+5;y++){const gi=((y-4)%10+10)%10,zi=((y-4)%12+12)%12;r.push({y,g:TG[gi],z:DZ[zi],sx:SX[zi]})}return r;}
function getLiuYue(year){const baseMap=[2,4,6,8,0];const ygi=((year-4)%10+10)%10;const startGan=(baseMap[ygi%5]+0)%10;const res=[];const names=['寅月(正月)','卯月(二月)','辰月(三月)','巳月(四月)','午月(五月)','未月(六月)','申月(七月)','酉月(八月)','戌月(九月)','亥月(十月)','子月(冬月)','丑月(腊月)'];const jieNames=['立春','惊蛰','清明','立夏','芒种','小暑','立秋','白露','寒露','立冬','大雪','小寒'];for(let i=0;i<12;i++){const gi=(startGan+i)%10;const zi=(2+i)%12;const jq=jqDate(year,i);const jqStr=jq?`${jq[0]}月${jq[1]}日${jieNames[i]}`:'';res.push({name:names[i],gz:TG[gi]+DZ[zi],jq:jqStr});}return res;}
function getShenShaLabels(b){const labels=[];const zh=[b.Y.z,b.M.z,b.D.z,b.H.z];const ch={'子':'午','午':'子','丑':'未','未':'丑','寅':'申','申':'寅','卯':'酉','酉':'卯','辰':'戌','戌':'辰','巳':'亥','亥':'巳'};const ha={'子':'未','未':'子','丑':'午','午':'丑','寅':'巳','巳':'寅','卯':'辰','辰':'卯','申':'亥','亥':'申','酉':'戌','戌':'酉'};const he={'子':'丑','丑':'子','寅':'亥','亥':'寅','卯':'戌','戌':'卯','辰':'酉','酉':'辰','巳':'申','申':'巳','午':'未','未':'午'};const po={'子':'酉','酉':'子','丑':'辰','辰':'丑','寅':'亥','亥':'寅','卯':'午','午':'卯','巳':'申','申':'巳','未':'戌','戌':'未'};const zx={'辰':'辰','午':'午','酉':'酉','亥':'亥'};const mk=v=>({bg:'color-mix(in srgb,var(--c-'+v+') 12%,transparent)',co:'var(--c-'+v+')',bd:'color-mix(in srgb,var(--c-'+v+') 26%,transparent)'});const mp={green:mk('green'),red:mk('red'),orange:mk('orange'),yellow:mk('yellow')};for(let i=0;i<4;i++)for(let j=i+1;j<4;j++){const a=zh[i],bb=zh[j];if(ch[a]===bb)labels.push({t:a+bb+'·冲',...mp.red});if(ha[a]===bb)labels.push({t:a+bb+'·害',...mp.orange});if(he[a]===bb)labels.push({t:a+bb+'·合',...mp.green});if(po[a]===bb)labels.push({t:a+bb+'·破',...mp.yellow});if(zx[a]===bb)labels.push({t:a+'·自刑',...mp.red});}const zset=new Set(zh);if(zset.has('寅')&&zset.has('巳')&&zset.has('申'))labels.push({t:'寅巳申·三刑',...mp.red});if(zset.has('丑')&&zset.has('戌')&&zset.has('未'))labels.push({t:'丑戌未·三刑',...mp.red});return labels;}
function getTodayGZ(){const now=new Date();const y=now.getFullYear(),m=now.getMonth()+1,d=now.getDate();const dji=getDayPillarIndex(y,m,d);const dgi=dji%10,dzi=dji%12;const mp=getMonthPillar(y,m,d);const mzi=(mp.mi+2)%12;const mgi=([2,4,6,8,0][(((mp.yp-4)%10+10)%10)%5]+mp.mi)%10;const yp=mp.yp;const ygi=((yp-4)%10+10)%10, yzi=((yp-4)%12+12)%12;return TG[ygi]+DZ[yzi]+'年 '+TG[mgi]+DZ[mzi]+'月 '+TG[dgi]+DZ[dzi]+'日';}

export { mkBazi, mkWx, mkSs, mkShenSha, mkDy, mkLn, getLiuYue, getShenShaLabels, getTodayGZ };
