import { getCtx } from '../state/context.js';
import { getTodayGZ } from '../engines/bazi.js';
import { toolPageShell, setToolOutput } from './shared.js';

function closeToolPage(){document.getElementById('toolModal').classList.remove('open');if(window._returnToAI){window._returnToAI=false;setTimeout(()=>openAsk(),120);}}
function openToolPage(type){
  window._activeTool=type;
  const d=getCtx(),modal=document.getElementById('toolModal'),out=document.getElementById('toolModalContent');
  if(!d||!modal||!out)return;
  const av={color:d.wx.ys==='木'?'青绿':d.wx.ys==='火'?'红紫':d.wx.ys==='土'?'黄棕':d.wx.ys==='金'?'白银':'黑蓝',dir:d.wx.ys==='木'?'东方':d.wx.ys==='火'?'南方':d.wx.ys==='土'?'中央':d.wx.ys==='金'?'西方':'北方'};
  const data=(items,note='')=>'<div class="tool-page-data">'+items.map(x=>'<div><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'</div>'+(note?'<div class="tool-page-note">'+note+'</div>':'');
  if(type==='wealth')out.innerHTML=toolPageShell('财运与理财罗盘','命盘趋势 + 你的现金流输入，生成可执行的理财优先级。',data([['当前财运',d.ws+' / 100'],['财富节奏',d.ws>=70?'可争取增收与谈价':'以稳健积累为主'],['命盘取向',d.wx.st?'分散配置，避免追高':'先建立储蓄与安全垫'],['数据边界','不构成投资建议']])+'<div class="tool-form-row"><input id="wealthIncome" type="number" placeholder="月到手收入"><input id="wealthCost" type="number" placeholder="月固定支出"><input id="wealthCash" type="number" placeholder="现有储蓄"></div><div class="tool-form-row"><button class="tool-primary" onclick="runWealthTool()">生成现金流方案</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='career')out.innerHTML=toolPageShell('转行与副业测评','命盘阶段 + 现实准备度，输出转行与副业的行动方案。',data([['当前事业',d.cs+' / 100'],['流年重点',d.cLnSS||'稳定积累'],['大运阶段',d.cDy.g+d.cDy.z],['评估原则','能力、现金流、机会同步判断']])+'<div class="tool-form-row"><select id="careerGoal"><option>转行</option><option>副业</option><option>创业</option></select><select id="careerReady"><option value="1">已有技能与作品</option><option value="2">有方向，仍需准备</option><option value="3">尚未明确方向</option></select></div><div class="tool-form-row"><button class="tool-primary" onclick="runCareerTool()">开始测评</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='date')out.innerHTML=toolPageShell('重要事项择日助手','选择事项与目标日期，生成准备清单和沟通提醒。','<div class="tool-form-row"><select id="dateEvent"><option>签约合作</option><option>面试入职</option><option>搬家出行</option><option>表白沟通</option></select><input id="dateTarget" type="date"></div><div class="tool-form-row"><button class="tool-primary" onclick="runDateTool()">生成准备方案</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='style')out.innerHTML=toolPageShell('能量穿搭与工位风水','按场景输出穿搭、桌面和专注环境建议。',data([['有利元素',d.wx.ys],['推荐颜色',av.color+'系'],['有利方位',av.dir],['基础原则','舒适、整洁、光线稳定']])+'<div class="tool-form-row"><select id="styleScene"><option>重要沟通</option><option>面试汇报</option><option>专注工作</option><option>休息恢复</option></select><button class="tool-primary" onclick="runStyleTool()">生成方案</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='layoff')out.innerHTML=toolPageShell('裁员风险检测','现实风险信号 + 现金流缓冲 + 当前事业节奏，生成行动预案。','<div class="tool-form-row"><select id="layoffSignal"><option value="1">公司稳定，岗位核心</option><option value="2">业务调整，工作可交接</option><option value="3">部门收缩，已有明确信号</option></select><select id="layoffBuffer"><option value="1">储蓄可覆盖 6 个月以上</option><option value="2">储蓄可覆盖 3—6 个月</option><option value="3">储蓄不足 3 个月</option></select></div><div class="tool-form-row"><select id="layoffMarket"><option value="1">简历与作品集已更新</option><option value="2">有零散机会但未准备</option><option value="3">尚未准备求职渠道</option></select><button class="tool-primary" onclick="runLayoffTool()">生成预案</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='daily')out.innerHTML=toolPageShell('今日日签','选择今天最想聚焦的方向，生成一页专属行动日签。',data([['今日',''+getTodayGZ()],['有利元素',d.wx.ys+' · '+av.color+' · '+av.dir],['今日基调','先完成，再优化'],['使用方式','选择一个重点后生成日签']])+'<div class="tool-form-row"><select id="dailyFocus"><option>推进工作</option><option>关系沟通</option><option>学习积累</option><option>休息恢复</option></select><button class="tool-primary" onclick="runDailyTool()">生成日签</button></div>');
  else if(type==='name')out.innerHTML=toolPageShell('智能起名工具','输入姓氏与偏好，生成用字方向与名称灵感。','<div class="tool-form-row"><input id="nameSurname" placeholder="输入姓氏"><select id="nameStyle"><option>简洁现代</option><option>温润典雅</option><option>大气坚定</option></select><button class="tool-primary" onclick="runNameTool()">生成</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='oracle')out.innerHTML=toolPageShell('摇签问卜','将问题聚焦到一件可行动的事，随机签文用于自我反思。','<div class="tool-form-row"><select id="oracleArea"><option>事业选择</option><option>关系沟通</option><option>财富计划</option><option>内在状态</option></select><input id="oracleQuestion" placeholder="例如：这周是否该主动沟通？"></div><div class="tool-form-row"><button class="tool-primary" onclick="runOracleTool()">摇三签</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='lottery')out.innerHTML=toolPageShell('双色球 / 超级大乐透','随机组合仅供娱乐；不使用命盘预测中奖，也不建议超出娱乐预算。','<div class="tool-form-row"><select id="lotteryType"><option value="ssq">双色球</option><option value="dlt">超级大乐透</option></select><select id="lotteryCount"><option value="1">1 注</option><option value="3">3 注</option><option value="5">5 注</option></select></div><div class="tool-form-row"><button class="tool-primary" onclick="runLotteryTool()">生成随机组合</button></div><div class="tool-output" id="toolOutput"></div>');
  else if(type==='zodiac')out.innerHTML=toolPageShell('生肖合冲分析','基于你的生肖 '+d.b.sx+'，查看与对方生肖的相处提醒。','<div class="tool-form-row"><select id="zodiacOther"><option>鼠</option><option>牛</option><option>虎</option><option>兔</option><option>龙</option><option>蛇</option><option>马</option><option>羊</option><option>猴</option><option>鸡</option><option>狗</option><option>猪</option></select><button class="tool-primary" onclick="runZodiacTool()">开始分析</button></div><div class="tool-output" id="toolOutput"></div>');
  else out.innerHTML=toolPageShell('八字合盘 · 关系分析','为对方真实排盘，逐柱比对日主、五行与干支关系。',data([['你的日主',d.dg+d.dw],['你的用神',d.wx.ys],['比对方式','日柱（夫妻宫）+ 五行互补 + 干支刑冲合害'],['结果性质','用于理解差异，不预测结局']])+'<div class="tool-form-row"><input id="relName" placeholder="对方称呼（可选）"><select id="relFocus"><option>亲密关系</option><option>朋友合作</option><option>家人沟通</option></select></div><div class="tool-form-row"><input id="relDate" type="date" aria-label="对方出生日期"><select id="relHour" aria-label="对方出生时辰"><option value="">时辰不详（三柱比对）</option><option value="0">子 23:00–00:59</option><option value="1">丑 01:00–02:59</option><option value="2">寅 03:00–04:59</option><option value="3">卯 05:00–06:59</option><option value="4">辰 07:00–08:59</option><option value="5">巳 09:00–10:59</option><option value="6">午 11:00–12:59</option><option value="7">未 13:00–14:59</option><option value="8">申 15:00–16:59</option><option value="9">酉 17:00–18:59</option><option value="10">戌 19:00–20:59</option><option value="11">亥 21:00–22:59</option></select></div><div class="tool-panel-note">不知道对方时辰也能算：日柱不依赖时辰，夫妻宫结论依然精确。</div><div class="tool-form-row"><button class="tool-primary" onclick="runRelationTool()">开始合盘</button></div><div class="tool-output" id="toolOutput"></div>');
  modal.classList.add('open');
}

export { closeToolPage, openToolPage };
